export const scenarios = [
  ['introductions','Introduce yourself','A1','Meet a new classmate','classmate'],
  ['college','First day at college','A1','Tell a classmate about your course','classmate'],
  ['canteen','Order at a canteen','A1','Ask for food politely','customer'],
  ['directions','Ask for directions','A1','Find the library','classmate'],
  ['shopping','Buy a notebook','A1','Ask about prices and sizes','customer'],
  ['hobbies','Talk about hobbies','A2','Share what you enjoy','classmate'],
  ['weekend','Weekend plans','A2','Make a simple plan','classmate'],
  ['travel','Travel by train','A2','Ask about a ticket','customer'],
  ['phone','Make a phone call','A2','Leave a clear message','teacher'],
  ['appointment','Reschedule an appointment','B1','Explain a conflict and suggest a time','teacher'],
  ['interview','First job interview','B1','Explain why you want the role','interviewer'],
  ['project','Explain a project','B1','Describe your work and result','interviewer'],
  ['presentation','Present an idea','B1','Open a short presentation','teacher'],
  ['customer','Help a customer','B1','Clarify a request','customer'],
  ['complaint','Incorrect order','B1','Resolve a mistake politely','customer'],
  ['feedback','Give constructive feedback','B2','Be specific and kind','classmate'],
  ['negotiation','Negotiate a price','B2','Make a reasonable counteroffer','customer'],
  ['meeting','Join a meeting','B2','Summarize a point and ask a question','teacher'],
  ['debate','Discuss remote work','C1','Support an opinion with an example','teacher'],
  ['leadership','Handle a team conflict','C1','Explain a balanced solution','interviewer']
].map(([id,title,level,objective,role])=>({id,title,level,objective,role}));

export const lessons = [
 ['greetings','Friendly greetings','A1','Greet someone and ask how they are.','Hi, I’m Krishna. How are you today?'],
 ['names','Names and introductions','A1','Introduce yourself clearly.','My name is Krishna, and I study computer science.'],
 ['questions','Simple questions','A1','Ask a useful follow-up question.','What do you like to study?'],
 ['courtesy','Polite requests','A1','Request something politely.','Could I have a glass of water, please?'],
 ['numbers','Prices and numbers','A1','Ask about a price.','How much does this notebook cost?'],
 ['routine','Daily routine','A2','Describe a regular habit.','I usually study after dinner.'],
 ['past','Yesterday and last week','A2','Tell a short story in the past.','Yesterday I visited the library and borrowed a book.'],
 ['future','Future plans','A2','Describe a plan.','I’m going to practice English tomorrow morning.'],
 ['directions','Finding places','A2','Ask for and confirm directions.','Is the station near the market?'],
 ['opinions','Simple opinions','A2','Give an opinion and a reason.','I prefer trains because they are comfortable.'],
 ['experiences','Share an experience','B1','Describe an experience and its result.','I worked on a group project and learned to coordinate tasks.'],
 ['clarify','Ask for clarification','B1','Check that you understood.','Could you explain what you mean by the deadline?'],
 ['interview','Interview answers','B1','Answer with a concrete example.','I improved the page speed by reducing image sizes.'],
 ['meeting','Meeting contributions','B1','Add a useful point in a meeting.','I agree, and I would also consider the testing time.'],
 ['repair','Correct a misunderstanding','B1','Restate your meaning calmly.','I meant next Thursday, not this Thursday.'],
 ['compare','Compare options','B2','Compare two options with tradeoffs.','The first option is cheaper, while the second is easier to maintain.'],
 ['persuade','Make a proposal','B2','Make a proposal with a reason.','I suggest a short pilot so we can measure the result.'],
 ['feedback','Give helpful feedback','B2','Give a specific suggestion.','Your opening was clear; one example would make it stronger.'],
 ['nuance','Express uncertainty','C1','Qualify a claim accurately.','The results suggest an improvement, although the sample is small.'],
 ['synthesis','Summarize a discussion','C1','Summarize agreement and open questions.','We agree on the goal; the timeline still needs discussion.']
].map(([id,title,level,objective,example])=>({id,title,level,objective,example}));
