const root=document.querySelector('#app');
const state={page:'home',data:null,scenario:'introductions',lesson:null,turns:[],feedback:null,message:null,authMode:'register'};
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,method='GET',payload) {
  const res=await fetch('/api/'+path,{method,credentials:'same-origin',headers:payload?{'Content-Type':'application/json'}:{},body:payload?JSON.stringify(payload):undefined});
  const data=await res.json(); if(!res.ok) throw new Error(data.error?.message||'Request failed'); return data;
}
async function refresh(){state.data=await api('bootstrap');render()}
function show(page){state.page=page;state.message=null;render();window.scrollTo(0,0)}
function message(text,error=false){state.message={text,error};render()}
const nav=['home','practice','lessons','progress','profile'];
function shell(content){
  const user=state.data.user;
  root.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">speak<em>daily.</em></div><nav class="nav" aria-label="Main navigation">${nav.map(n=>`<button data-page="${n}" class="${state.page===n?'active':''}" ${state.page===n?'aria-current="page"':''}>${n[0].toUpperCase()+n.slice(1)}</button>`).join('')}</nav><div class="sidebar-foot">A little practice, every day.<br>Development preview · simulated tutor</div></aside><main class="main"><header class="top"><span class="eyebrow">English, one conversation at a time</span><span class="pill">${user?'Hi, '+escapeHtml(user.email.split('@')[0]):'Guest · '+state.data.guestRemaining+' turns left'}</span></header>${state.message?`<div role="status" class="notice ${state.message.error?'error':''}">${escapeHtml(state.message.text)}</div>`:''}${content}<p class="footer-note">Development preview: tutor replies are simulated text. Voice calls, AI correction, pronunciation assessment, purchases, and ads are not active.</p></main></div>`;
}
function home(){shell(`<div class="hero"><div><div class="eyebrow" style="color:#c6ee9a">Your daily speaking space</div><h1>Find your words.<br>Build your confidence.</h1><p>Practise a short English exchange, review an example, and keep going at your own pace.</p><button class="btn" data-page="practice">Start practicing →</button></div><div class="hero-art"><div class="bubble">“Tell me about your day.”</div><div class="bubble second">“It was interesting!” ✨</div></div></div><div class="section-head"><h2>Choose your next step</h2></div><div class="cards3"><div class="card"><div class="emoji">💬</div><h3>Practice a conversation</h3><p class="muted">Try a realistic prompt and add details to your answer.</p><button class="btn secondary" data-page="practice">Explore scenarios</button></div><div class="card"><div class="emoji">📚</div><h3>Learn in minutes</h3><p class="muted">Short lessons with a clear goal and example.</p><button class="btn secondary" data-page="lessons">See lessons</button></div><div class="card"><div class="emoji">🌱</div><h3>See your progress</h3><p class="muted">Track completed lessons and practice turns.</p><button class="btn secondary" data-page="progress">View progress</button></div></div>`)}
function practice(){const s=state.data.scenarios.find(s=>s.id===state.scenario)||state.data.scenarios[0];shell(`<div class="eyebrow">Practice / Development simulation</div><h1 class="page-title">Practice a conversation</h1><p class="intro">Choose a situation and type a response. Tutor text is a scripted development simulation; it does not assess your grammar or speech.</p><div class="practice-layout"><section class="card"><div class="field"><label for="scenario">Situation</label><select id="scenario">${state.data.scenarios.map(x=>`<option value="${x.id}" ${x.id===s.id?'selected':''}>${escapeHtml(x.title)} · ${x.level}</option>`).join('')}</select></div><p class="muted">${escapeHtml(s.objective)} · ${escapeHtml(s.role)} role</p><div class="transcript" aria-live="polite"><div class="turn tutor"><small>SIMULATED TUTOR</small>${escapeHtml(s.objective)}. What would you say?</div>${state.turns.map(t=>`<div class="turn ${t.role}"><small>${t.role==='learner'?'YOU':'SIMULATED TUTOR'}</small>${escapeHtml(t.text)}</div>`).join('')}</div><form id="practice-form"><div class="field"><label for="practice-input">Your response</label><textarea id="practice-input" name="input" maxlength="500" required placeholder="Type what you would say…"></textarea></div><div class="actions"><button class="btn dark" type="submit">Send response</button><span class="muted small">${state.data.user?'Progress saved to your account':state.data.guestRemaining+' free guest turns remain'}</span></div></form></section><aside class="card"><div class="meta">Practice guide</div><h3>Try one more detail</h3><p class="muted">A specific example makes your answer easier to follow.</p>${state.feedback?`<div class="notice"><b>Next step</b><br>${escapeHtml(state.feedback.nextStep)}<br><span class="small">${escapeHtml(state.feedback.notice)}</span></div>`:''}<p class="small muted">Voice conversation and measured corrections will arrive with the live provider integration.</p></aside></div>`)}
function lessons(){const rows=state.data.lessons.map(l=>`<div class="card lesson-row"><div><span class="badge">${l.level}</span><h3>${escapeHtml(l.title)}</h3><p class="muted">${escapeHtml(l.objective)}</p></div><button class="btn secondary" data-lesson="${l.id}">${state.data.completed.includes(l.id)?'Review':'Open'}</button></div>`).join('');shell(`<div class="eyebrow">Short, practical lessons</div><h1 class="page-title">Lessons</h1><p class="intro">Twenty original lessons, from first conversations to nuanced workplace English.</p>${state.lesson?lessonDetail():`<div class="list">${rows}</div>`}`)}
function lessonDetail(){const l=state.data.lessons.find(x=>x.id===state.lesson);return `<div class="card"><span class="badge">${l.level}</span><h2 style="margin-top:14px">${escapeHtml(l.title)}</h2><p>${escapeHtml(l.objective)}</p><div class="notice"><b>Example response</b><br>“${escapeHtml(l.example)}”</div><p>Say the example aloud or write your own version. You can repeat it in a different situation.</p><div class="actions"><button class="btn dark" data-complete="${l.id}">Mark complete</button><button class="btn secondary" data-close-lesson="1">Back to lessons</button></div></div>`}
function progress(){shell(`<div class="eyebrow">Your activity</div><h1 class="page-title">Progress</h1><p class="intro">These numbers count completed activities. They are not proficiency or fluency scores.</p><div class="grid"><div class="card"><div class="meta">Conversation turns</div><div class="stat">${state.data.practiceCount}</div><p class="muted">Text practice submitted</p></div><div class="card"><div class="meta">Lessons completed</div><div class="stat">${state.data.completed.length} / 20</div><p class="muted">Available to revisit any time</p></div></div>${!state.data.user?'<div class="notice">Create an account to keep this guest progress across devices. Your current activity will migrate when you register in this browser.</div>':''}`)}
function profile(){const p=state.data.profile;const user=state.data.user;shell(`<div class="eyebrow">Account & preferences</div><h1 class="page-title">${user?'Your profile':'Save your progress'}</h1>${user?`<div class="grid"><form class="card" id="profile-form"><h2>Learning preferences</h2><div class="field"><label for="goal">Learning goal</label><input id="goal" name="goal" maxlength="80" required value="${escapeHtml(p?.goal||'Speak more confidently')}"></div><div class="field"><label for="level">Approximate level</label><select id="level" name="level">${['unsure','A1','A2','B1','B2','C1','C2'].map(x=>`<option ${p?.level===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label for="language">Explanation language</label><select id="language" name="language">${['English','Hindi','Hinglish'].map(x=>`<option ${p?.language===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label for="interests">Interests</label><input id="interests" name="interests" maxlength="200" value="${escapeHtml(p?.interests||'')}"></div><div class="field"><label for="dailyMinutes">Daily target in minutes</label><input id="dailyMinutes" name="dailyMinutes" type="number" min="5" max="60" value="${p?.dailyMinutes||10}"></div><button class="btn dark">Save preferences</button></form><div class="card"><h2>Account</h2><p>${escapeHtml(user.email)}</p><p class="muted">Account deletion removes learning records from this development database immediately. Backup retention is not configured.</p><div class="actions"><button class="btn secondary" id="logout">Log out</button><button class="btn outline danger" id="delete-account">Delete account</button></div></div></div>`:`<div class="auth card"><h2>${state.authMode==='register'?'Create an account':'Sign in'}</h2><p class="muted">${state.authMode==='register'?'Your guest activity in this browser moves to the new account.':'Welcome back.'}</p><form id="auth-form"><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" required autocomplete="email"></div><div class="field"><label for="password">Password</label><input id="password" name="password" type="password" minlength="12" required autocomplete="${state.authMode==='register'?'new-password':'current-password'}"></div><button class="btn dark">${state.authMode==='register'?'Create account':'Sign in'}</button></form><button class="inline" id="auth-toggle">${state.authMode==='register'?'Already have an account? Sign in':'New here? Create an account'}</button></div>`}`)}
function render(){if(!state.data)return;({home,practice,lessons,progress,profile}[state.page]||home)()}
root.addEventListener('click',async e=>{
  const page=e.target.closest('[data-page]')?.dataset.page;if(page)return show(page);
  const lesson=e.target.closest('[data-lesson]')?.dataset.lesson;if(lesson){state.lesson=lesson;return render()}
  if(e.target.closest('[data-close-lesson]')){state.lesson=null;return render()}
  const complete=e.target.closest('[data-complete]')?.dataset.complete;if(complete){try{await api('lessons/complete','POST',{lessonId:complete});state.lesson=null;await refresh()}catch(err){message(err.message,true)}return}
  if(e.target.id==='auth-toggle'){state.authMode=state.authMode==='register'?'login':'register';return render()}
  if(e.target.id==='logout'){await api('auth/logout','POST');await refresh();return message('You are signed out.')}
  if(e.target.id==='delete-account'){if(!confirm('Delete this account and its saved learning progress? This cannot be undone.'))return;await api('account/delete','POST');state.page='home';await refresh();return message('Your account was deleted.')}
});
root.addEventListener('change',e=>{if(e.target.id==='scenario'){state.scenario=e.target.value;state.turns=[];state.feedback=null;render()}});
root.addEventListener('submit',async e=>{
  e.preventDefault();const form=e.target;const b=form.querySelector('button[type=submit],button.btn');if(b)b.disabled=true;
  try{
    const d=Object.fromEntries(new FormData(form));
    if(form.id==='practice-form'){const r=await api('practice','POST',{scenarioId:state.scenario,input:d.input});state.turns.push({role:'learner',text:d.input},{role:'tutor',text:r.reply});state.feedback=r.feedback;await refresh()}
    if(form.id==='auth-form'){await api(`auth/${state.authMode}`,'POST',d);await refresh();message('Your account is ready. Guest progress from this browser has been saved.')}
    if(form.id==='profile-form'){await api('profile','POST',{goal:d.goal,level:d.level,language:d.language,interests:d.interests,dailyMinutes:Number(d.dailyMinutes)});await refresh();message('Preferences saved.')}
  }catch(err){message(err.message,true)}finally{if(b)b.disabled=false}
});
refresh().catch(err=>{root.textContent='Could not connect to SpeakDaily. Please refresh the page. '+err.message});
